<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">

	<meta name="description" content="{$web->description}">
	<meta name="keywords" content="{$web->keywords}">
	<meta name="author" content="{$web->author}">
	<meta name="robots" content="{$web->robots}" n:ifset="$web->robots">

	<title>{ifset $pageTitle}{$pageTitle} | {/if}{$web->defaultTitle}</title>

	<link rel="stylesheet" href="/include/blueprint/screen.css"   type="text/css" media="screen, projection">
	<link rel="stylesheet" href="/include/blueprint/print.css" type="text/css" media="print">
	<!--[if IE]><link rel="stylesheet" href="/include/blueprint/ie.css" type="text/css" media="screen, projection"><![endif]-->

	<link rel="stylesheet" media="screen,projection,tv" href="/include/screen.css" type="text/css">
	<link media="screen" rel="stylesheet" href="/include/colorbox.css">
	<script type="text/javascript" src="/include/jquery-min.js"></script>
	<script type="text/javascript" src="/include/jquery.colorbox-min.js"></script>
	<script type="text/javascript" n:syntax="off">
		$(document).ready(function(){
			$("a[rel='galImg']").colorbox({ 
				transition:"none",
				loop: false,
				slideshow: true,
				slideshowAuto: false,
				scalePhotos: true,
				maxWidth: "90%",
				maxHeight: "90%",
				slideshowSpeed: <?php echo $timeout; ?>,
				slideshowStart: "<?php echo translate("start slideshow"); ?>",
				slideshowStop: "<?php echo translate("stop slideshow"); ?>",
				current: "{current} <?php echo translate("of");?> {total}",
				next: "<?php echo translate("next"); ?>",
				previous: "<?php echo translate("previous"); ?>",
				close: "<?php echo translate("close"); ?>"
			});
		});
	</script>
	<style type="text/css">
		.thumb a {
			width: <?php echo Environment::getConfig("gallery")->width; ?>px;
		}
	</style>
</head>

<body>
	<div class="container">
		{if isSet($showGDWarning)}
		<div class="error">
			{toLang "Support for GD PHP module is missing, thumbs won't work."}
		</div>
		{/if}
		<hr>
			<h1>{$web->defaultTitle}</h1>
		<hr>

		<hr class="space clear">

		<div class="span-5 colborder">
			<h2>{toLang "Galleries"}</h2>
			{if count($menu) > 0}
				<ul class="menu">
					{foreach $menu as $row}
						{var $name => getGalleryName($row)}
						{var $count => numberOfItems($row)}
						<li><a {if $currentGallery == $row}class="highlight"{/if} href="/gallery/{$row|url}" title="{toLang "Open gallery"} {$name} ({$count})">{$name|truncate:20} <span class="count">({$count})</span></a></li>
					{/foreach}
				</ul>
			{else}
				<p>{toLang "There are no galleries."}</p>
			{/if}
		</div>

		<div class="span-18 last">
			{block #content}
				
			{/block}
		</div>
		<div class="clear" id="footer">
			{toLang "Powered by Wasp Gallery"} &copy; 2010 <a href="http://www.jandrabek.cz">Jan Drabek</a>
			{if !empty($_SESSION)}
			| <a href="/logout/">{toLang "Log out"}</a>
			{/if}
		</div>
		<hr>
	</div>

</body>
</html>
